#!/usr/bin/env bash
# Interactive first-time setup: generates secrets, asks a few questions, and
# writes .env. Safe to re-run — it will ask before overwriting an existing
# .env.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

for bin in docker openssl; do
	if ! command -v "$bin" >/dev/null 2>&1; then
		echo "error: $bin is required but not on PATH." >&2
		exit 1
	fi
done
if ! docker compose version >/dev/null 2>&1; then
	echo "error: 'docker compose' (the v2 plugin) is required." >&2
	exit 1
fi

if [ -f .env ]; then
	read -rp ".env already exists. Overwrite it? [y/N] " reply
	case "$reply" in
	[yY]*) ;;
	*)
		echo "Leaving .env untouched."
		exit 0
		;;
	esac
fi

prompt() {
	# prompt <var-name> <question> <default>
	local __var=$1 __question=$2 __default=$3 __reply
	read -rp "$__question [$__default] " __reply
	printf -v "$__var" '%s' "${__reply:-$__default}"
}

echo "== TrP Tools setup =="
echo "Press enter to accept the default shown in [brackets]."
echo

prompt BASE_URL "Public URL of the API (BASE_URL):" "http://localhost:3001"
prompt FRONTEND_URL "Public URL of the site (FRONTEND_URL):" "http://localhost:3000"

s3_default="$(printf '%s' "$BASE_URL" | sed -E 's#(https?://[^:/]+).*#\1:9000#')"
prompt S3_PUBLIC_URL "Public URL uploaded images are served from (S3_PUBLIC_URL):" "$s3_default"

echo
echo "Roblox OAuth (leave blank to fill in later — sign-in won't work until"
echo "these are set; see the README for how to register an app):"
prompt ROBLOX_CLIENT_ID "  Roblox client ID:" ""
prompt ROBLOX_CLIENT_SECRET "  Roblox client secret:" ""
prompt SITE_ADMINS "Comma-separated Roblox user IDs to grant site-admin:" ""

echo
read -rp "Pull the default TrP Tools policies (terms/privacy) from TrP-Labs/Policies now? [Y/n] " pull_reply
case "$pull_reply" in
[nN]*) ;;
*) ./scripts/pull-policies.sh ;;
esac

echo
echo "Generating secrets..."
ENCRYPTION_KEY="$(openssl rand -base64 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 24)"
S3_ACCESS_KEY="$(openssl rand -hex 12)"
S3_SECRET_KEY="$(openssl rand -hex 24)"

cat >.env <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

BASE_URL=$BASE_URL
FRONTEND_URL=$FRONTEND_URL

# Encrypts stored Roblox OAuth tokens and group Open Cloud keys.
ENCRYPTION_KEY=$ENCRYPTION_KEY

ROBLOX_CLIENT_ID=$ROBLOX_CLIENT_ID
ROBLOX_CLIENT_SECRET=$ROBLOX_CLIENT_SECRET

# Comma separated Roblox user IDs granted the site-wide admin rank.
SITE_ADMINS=$SITE_ADMINS

# --- Postgres -----------------------------------------------------------
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# --- Object storage (MinIO) ----------------------------------------------
S3_BUCKET=trptools
S3_ACCESS_KEY=$S3_ACCESS_KEY
S3_SECRET_KEY=$S3_SECRET_KEY
S3_PUBLIC_URL=$S3_PUBLIC_URL

# Image tag to deploy. "latest" tracks main; pin to a release like v1.2.3
# for a stable rollout.
TAG=latest
EOF
chmod 600 .env

echo
echo "Wrote .env. Next:"
echo "  docker compose up -d"
echo
echo "Then open $FRONTEND_URL"
if [ -z "$ROBLOX_CLIENT_ID" ]; then
	echo
	echo "Roblox credentials are blank, so sign-in won't work yet — see the"
	echo "README's 'Setting up Roblox' section, then set ROBLOX_CLIENT_ID and"
	echo "ROBLOX_CLIENT_SECRET in .env and run 'docker compose up -d' again."
fi
